In [1]:
import numpy as np

## Datatypes and Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size # number of elements in each array

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a dataframe from a numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [16]:
sample_array = np.array([1, 2, 3])
sample_array.dtype

dtype('int64')

In [17]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
type(ones)

numpy.ndarray

In [20]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[9, 7, 9, 0, 7],
       [6, 1, 4, 0, 5],
       [7, 9, 6, 4, 2]])

In [23]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.19049628, 0.48238575, 0.23362071],
       [0.10950663, 0.67767268, 0.26049011],
       [0.73567636, 0.20417891, 0.65444667],
       [0.47723039, 0.66408953, 0.26190835],
       [0.61978745, 0.45454908, 0.25400303]])

In [24]:
random_array_2.shape

(5, 3)

In [25]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.95698496, 0.29305422, 0.80028302],
       [0.5130979 , 0.41256899, 0.85651675],
       [0.55038452, 0.61343426, 0.39325487],
       [0.01176024, 0.80830636, 0.02282367],
       [0.11671212, 0.47630026, 0.63828106]])

## Viewing arrays and matrices

In [26]:
np.unique(random_array_3)

array([0.01176024, 0.02282367, 0.11671212, 0.29305422, 0.39325487,
       0.41256899, 0.47630026, 0.5130979 , 0.55038452, 0.61343426,
       0.63828106, 0.80028302, 0.80830636, 0.85651675, 0.95698496])

In [28]:
a1[0]

1

In [30]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [29]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [31]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[5, 9, 8, 6, 5],
         [6, 7, 2, 1, 8],
         [5, 3, 6, 2, 2],
         [8, 9, 3, 4, 1]],

        [[5, 9, 5, 3, 9],
         [8, 1, 7, 1, 2],
         [7, 8, 0, 2, 4],
         [3, 5, 8, 1, 8]],

        [[3, 0, 1, 0, 3],
         [3, 3, 1, 2, 0],
         [0, 0, 4, 6, 0],
         [8, 2, 8, 4, 4]]],


       [[[5, 6, 8, 3, 6],
         [5, 5, 9, 6, 9],
         [2, 2, 0, 7, 7],
         [4, 7, 4, 7, 0]],

        [[4, 1, 7, 8, 5],
         [6, 8, 1, 8, 4],
         [6, 8, 5, 3, 2],
         [0, 8, 2, 4, 0]],

        [[0, 0, 8, 4, 5],
         [4, 4, 1, 3, 7],
         [8, 0, 0, 6, 1],
         [7, 0, 9, 7, 5]]]])

In [32]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [35]:
# Get the first 4 numbers of the inner most array
a4[:,:,:,:2]

array([[[[5, 9],
         [6, 7],
         [5, 3],
         [8, 9]],

        [[5, 9],
         [8, 1],
         [7, 8],
         [3, 5]],

        [[3, 0],
         [3, 3],
         [0, 0],
         [8, 2]]],


       [[[5, 6],
         [5, 5],
         [2, 2],
         [4, 7]],

        [[4, 1],
         [6, 8],
         [6, 8],
         [0, 8]],

        [[0, 0],
         [4, 4],
         [8, 0],
         [7, 0]]]])

## Manipulating and comparing arrays

### Arithmetic

In [36]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [37]:
a1

array([1, 2, 3])

In [38]:
a1 + ones

array([2., 3., 4.])

In [39]:
a1 - ones

array([0., 1., 2.])

In [40]:
a1 * ones

array([1., 2., 3.])

In [41]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [42]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [43]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [52]:
# a2 * a3   # can't broadcast

In [45]:
a1 / ones

array([1., 2., 3.])

In [46]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [47]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [48]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [49]:
np.add(a1, ones)

array([2., 3., 4.])

In [50]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [51]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

aggregation = performing the same operation on a number of things

In [56]:
listy_list = [1,2,3]
type(listy_list)

list

In [57]:
sum(listy_list)

6

In [58]:
np.sum(listy_list)

6

#### Use python functions (sum()) on python datatypes and use numpy's methods (np.sum()) on numpy arrays

In [61]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [63]:
massive_array[:10]

array([0.59275327, 0.2063609 , 0.45968738, 0.22840729, 0.36789716,
       0.01841118, 0.61463326, 0.46562943, 0.37273135, 0.56409718])

In [64]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

3.55 ms ± 138 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
18.5 µs ± 252 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [65]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [66]:
np.mean(a2)

3.6333333333333333

In [67]:
np.max(a2)

6.5

In [68]:
np.min(a2)

1.0

In [69]:
np.std(a2)

1.8226964152656422

In [70]:
np.var(a2)

3.3222222222222224

In [71]:
np.sqrt(np.var(a2))

1.8226964152656422

## Reshaping and transposing

In [72]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [73]:
a2.shape

(2, 3)

In [74]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [78]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [79]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [80]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [81]:
# transpose
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [82]:
a2.T.shape

(3, 2)

In [83]:
a3.shape

(2, 3, 3)

In [84]:
a3.T.shape

(3, 3, 2)

## Dot Product

In [85]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [86]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [87]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [88]:
# Element-wise multiplication
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [90]:
# Dot product
# np.dot(mat1, mat2)  # shape not aligned

In [91]:
# transpose to match the shape
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [92]:
mat2.shape, mat1.T.shape

((5, 3), (3, 5))

In [93]:
np.dot(mat2, mat1.T)

array([[ 51, 130,  67, 115, 111],
       [ 55,  76,  39,  69,  77],
       [ 72, 164,  85, 146, 145],
       [ 20,  33,  27,  37,  56],
       [ 15,  44,  34,  47,  64]])

## Comparison Operators

In [94]:
a1

array([1, 2, 3])

In [95]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [96]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [98]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [99]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [100]:
a1 > 5

array([False, False, False])

In [101]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

## Sorting arrays

In [103]:
random_array = np.random.randint(10, size=(3,5))
random_array

array([[2, 3, 8, 1, 3],
       [3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7]])

In [104]:
np.sort(random_array)

array([[1, 2, 3, 3, 8],
       [0, 1, 3, 3, 7],
       [0, 4, 7, 9, 9]])

In [105]:
# return the index of the array based on the value
np.argsort(random_array)

array([[3, 0, 1, 4, 2],
       [3, 4, 0, 1, 2],
       [2, 3, 4, 0, 1]])

In [106]:
a1

array([1, 2, 3])

In [107]:
np.argsort(a1)

array([0, 1, 2])

In [108]:
np.argmin(a1)

0

In [109]:
np.argmax(a1)

2

## Turn image into numpy array

In [110]:
from matplotlib.image import imread

panda = imread("numpy-panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [112]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [113]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.